version: '3.7'

services:
  workspace:
    build:
      context: .
      dockerfile: docker/debug/node/Dockerfile
    image: nest_workspace
    restart: on-failure
    container_name: nest_workspace
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    networks:
      - internal
    tty: true
    stdin_open: true
  mysql:
    image: mysql:5.7.31
    restart: always
    container_name: nest-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nest-base
      MYSQL_USER: nest-base
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - .mysql-data:/var/lib/mysql
    networks:
      - internal
networks:
  internal:
    name: internal
    driver: bridge
